version: "3.5"
services:
  app:
    image: yandex/clickhouse-server:latest
    network_mode: bridge
    volumes:
      - "$HOME/clickhouse-dev-data:/var/lib/clickhouse"
networks:
  default:
    external: true
    name: bridge
