#!/bin/sh

# PROVIDE: ss-local
# REQUIRE: NETWORKING

. /etc/rc.subr

name="ss_local"
rcvar=ss_local_enable

load_rc_config $name

: ${ss_local_enable:="NO"}
: ${ss_local_config="/usr/local/etc/shadowsocks-libev/config.json"}

command="/usr/sbin/daemon"
procname="/usr/local/bin/ss-local"
pidfile="/var/run/$name.pid"
required_files="${ss_local_config}"

command_args="-S -p $pidfile /usr/local/bin/ss-local -c $ss_local_config"

run_rc_command "$1"
